name: Github Action 실행하기

#master 브랜치에서 push 발생 시 실행되는 workflow
on:
  push:
    branches:
      - master
jobs:
  My-first-CICD-job:
    runs-on: ubuntu-latest
    steps:
      - name: simple-web
        run: echo "this is the first auto cicd step1"

  My-second-CICD-job:
    runs-on: ubuntu-latest
    steps:
      - name: 디렉토리 확인
        run: |
          ls -al
          pwd
      - name: file 생성
        run: |
          echo "new file" > test.txt
          ls -al

  My-third-CICD-job:
    runs-on: ubuntu-latest
    steps:
      - name: github 변수 확인
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY 

      - name: secret 변수 확인
        run: |
          echo ${{ secrets.MY_KEY }}
          echo ${{ secrets.MY_SECRET_KEY }}